
package tela;

import classes.*;
import static java.lang.System.exit;
import fabricaDAO.FabricaDAO;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
import javax.swing.text.DefaultFormatter;

/**
 *
 * @author xp_ci
 */
public class Tela extends javax.swing.JFrame {

    
    FabricaDAO fabricadao;
    ArrayList<QueijoPedido> listaQpedidos = new ArrayList();
    String ClienteAtual = "";
   
    
    
    
    
    public Tela(){
        initComponents();
        
        jtf_numcliente.setText(Integer.toString(Cliente.num_cliente));
        
        try{

             fabricadao = new FabricaDAO();

        }catch (ClassNotFoundException ex){

            System.out.println("\n Erro ao conectar: "+ex.toString());

        } catch (SQLException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtf_nomeC = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtf_emailC = new javax.swing.JTextField();
        jtf_cpfC = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtf_telefoneC = new javax.swing.JTextField();
        jtf_cartaoC = new javax.swing.JTextField();
        jtf_enderecoC = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtf_facebookC = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtf_instagramC = new javax.swing.JTextField();
        jbt_adicionarC = new javax.swing.JButton();
        jbt_atualizarC = new javax.swing.JButton();
        jbt_buscaNOME = new javax.swing.JButton();
        jbt_buscaCPF = new javax.swing.JButton();
        jbt_mostraTC = new javax.swing.JButton();
        jbt_removerC = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jtf_numcliente = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jtf_nomeCB = new javax.swing.JTextField();
        jtf_cpfCB = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jtf_idqueijo = new javax.swing.JTextField();
        jtf_valorVenda = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jtf_tipo = new javax.swing.JTextField();
        jtf_peso = new javax.swing.JTextField();
        jtf_lote = new javax.swing.JTextField();
        jbt_adicionarQ = new javax.swing.JButton();
        jbt_removerQ = new javax.swing.JButton();
        jbt_atualizarQ = new javax.swing.JButton();
        jbt_buscaLote = new javax.swing.JButton();
        jtf_loteB = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jtf_dtFab = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jbt_add = new javax.swing.JButton();
        jbt_finalizar = new javax.swing.JButton();
        jbt_buscarPedidos = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        jtf_idpedido2 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jtf_idqueijo2 = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jbt_removerQueijo = new javax.swing.JButton();
        jtf_cpfclienteP = new javax.swing.JTextField();
        jtf_qtd = new javax.swing.JTextField();
        jtf_prazo = new javax.swing.JTextField();
        btf_mostrar = new javax.swing.JButton();
        jtf_IDqueijo = new javax.swing.JTextField();
        jbt_sair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome :");

        jLabel2.setText("CPF :");

        jLabel3.setText("Email :");

        jLabel4.setText("Endereço :");

        jLabel5.setText("Telefone :");

        jLabel6.setText("N° do cartão :");

        jLabel7.setText("Facebook :");

        jLabel8.setText("Instagram :");

        jbt_adicionarC.setText("Adicionar");
        jbt_adicionarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_adicionarCActionPerformed(evt);
            }
        });

        jbt_atualizarC.setText("Atualizar");
        jbt_atualizarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_atualizarCActionPerformed(evt);
            }
        });

        jbt_buscaNOME.setText("Busca por nome");
        jbt_buscaNOME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_buscaNOMEActionPerformed(evt);
            }
        });

        jbt_buscaCPF.setText("Busca por CPF");
        jbt_buscaCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_buscaCPFActionPerformed(evt);
            }
        });

        jbt_mostraTC.setText("MOSTRAR TODOS");
        jbt_mostraTC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_mostraTCActionPerformed(evt);
            }
        });

        jbt_removerC.setText("Remover");
        jbt_removerC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_removerCActionPerformed(evt);
            }
        });

        jLabel17.setText("Total de Clientes =");

        jtf_numcliente.setText("0");

        jLabel22.setText("Nome :");

        jLabel23.setText("CPF :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(4, 4, 4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(4, 4, 4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtf_facebookC, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(jtf_nomeC)
                            .addComponent(jtf_cpfC)
                            .addComponent(jtf_emailC))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtf_telefoneC, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_enderecoC, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_cartaoC, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_instagramC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtf_nomeCB))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jbt_adicionarC, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbt_buscaNOME, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbt_buscaCPF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtf_cpfCB))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbt_removerC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jbt_mostraTC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbt_atualizarC, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtf_numcliente))
                                .addGap(13, 13, 13)))))
                .addGap(11, 11, 11))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtf_nomeC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jtf_enderecoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtf_cpfC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jtf_telefoneC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtf_emailC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jtf_cartaoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtf_facebookC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jtf_instagramC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbt_adicionarC)
                    .addComponent(jbt_atualizarC)
                    .addComponent(jbt_removerC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbt_mostraTC, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel22)
                        .addComponent(jLabel23)
                        .addComponent(jtf_nomeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtf_cpfCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_numcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbt_buscaCPF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbt_buscaNOME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Clientes", jPanel1);

        jLabel9.setText("ID do queijo :");

        jLabel10.setText("Valor de venda :");

        jLabel11.setText("Data de fabricação :");

        jLabel12.setText("Lote :");

        jLabel13.setText("Tipo :");

        jLabel14.setText("Peso :");

        jbt_adicionarQ.setText("Adicionar");
        jbt_adicionarQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_adicionarQActionPerformed(evt);
            }
        });

        jbt_removerQ.setText("Remover");
        jbt_removerQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_removerQActionPerformed(evt);
            }
        });

        jbt_atualizarQ.setText("Atualizar");
        jbt_atualizarQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_atualizarQActionPerformed(evt);
            }
        });

        jbt_buscaLote.setText("Buscar por lote");
        jbt_buscaLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_buscaLoteActionPerformed(evt);
            }
        });

        jLabel15.setText("Lote :");

        jButton11.setText("Mostrar todos");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jLabel16.setText("Veja todos os queijos");

        try {
            jtf_dtFab.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jtf_dtFab, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jtf_idqueijo))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jtf_valorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_lote)
                            .addComponent(jtf_tipo)
                            .addComponent(jtf_peso)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jbt_adicionarQ, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbt_removerQ, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbt_atualizarQ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(51, 51, 51)
                                .addComponent(jtf_loteB, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jbt_buscaLote, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel16)
                                .addGap(37, 37, 37)))))
                .addGap(16, 16, 16))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jtf_lote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jtf_dtFab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jtf_valorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jtf_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_idqueijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jtf_peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbt_adicionarQ)
                    .addComponent(jbt_removerQ)
                    .addComponent(jbt_atualizarQ))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_loteB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbt_buscaLote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Queijos", jPanel2);

        jLabel24.setText("CPF do cliente :");

        jLabel26.setText("ID do queijo :");

        jLabel27.setText("Quantidade :");

        jLabel28.setText("Prazo em dias :");

        jbt_add.setText("Adicionar");
        jbt_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_addActionPerformed(evt);
            }
        });

        jbt_finalizar.setText("Finalizar pedido");
        jbt_finalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_finalizarActionPerformed(evt);
            }
        });

        jbt_buscarPedidos.setText("Buscar pedidos do cliente");
        jbt_buscarPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_buscarPedidosActionPerformed(evt);
            }
        });

        jLabel18.setText("Insira o número do pedido que deseja atualizar ou deletar :");

        jLabel19.setText("Insira o ID do queijo a ser removido do pedido acima :");

        jButton12.setText("Deletar pedido");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jbt_removerQueijo.setText("Remover Queijo");
        jbt_removerQueijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_removerQueijoActionPerformed(evt);
            }
        });

        btf_mostrar.setText("Mostrar todos os pedidos");
        btf_mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btf_mostrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel28)
                                .addGap(31, 31, 31))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel24)
                                        .addGap(10, 10, 10))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jLabel26)
                                                .addGap(32, 32, 32))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jtf_IDqueijo)
                                                    .addComponent(jtf_qtd))
                                                .addGap(18, 18, 18)))
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jtf_cpfclienteP)
                                            .addComponent(jtf_prazo, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jbt_add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbt_finalizar))
                            .addComponent(btf_mostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbt_buscarPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(0, 10, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel19))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jtf_idqueijo2, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                            .addComponent(jtf_idpedido2)))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbt_removerQueijo, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(14, 14, 14))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtf_cpfclienteP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_IDqueijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jbt_add, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(jbt_finalizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbt_buscarPedidos)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel27)
                        .addComponent(jLabel28)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btf_mostrar)
                    .addComponent(jtf_prazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_qtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jtf_idpedido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jtf_idqueijo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbt_removerQueijo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        jTabbedPane1.addTab("Pedidos", jPanel4);

        jbt_sair.setText("SAIR");
        jbt_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_sairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(jbt_sair)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbt_sair)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbt_buscaCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_buscaCPFActionPerformed
        
        String cpf = jtf_cpfCB.getText();
        ArrayList <Cliente> listaC = fabricadao.mostracliente(cpf, 2);
        
        Cliente cliente = listaC.get(0);
        
        jtf_cpfC.setText(cliente.getCpf());
        jtf_nomeC.setText(cliente.getNome());
        jtf_telefoneC.setText(cliente.getTelefone());
        jtf_enderecoC.setText(cliente.getEndereco());
        jtf_instagramC.setText(cliente.getInstagram());
        jtf_emailC.setText(cliente.getEmail());
        jtf_facebookC.setText(cliente.getFacebook());
        jtf_cartaoC.setText(cliente.getCartao());
        
        
    }//GEN-LAST:event_jbt_buscaCPFActionPerformed

    private void jbt_buscaNOMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_buscaNOMEActionPerformed
        //Setar a MostraCliente->Tela1 com os parametros de busca, pode ser feito chamando uma função da tela1
        if(jtf_nomeCB.getText().equals("")){
            JOptionPane.showMessageDialog(null, "INFORME O NOME NO CAMPO DE BUSCA");
        }else{
        
            MostraCliente tela1 = new MostraCliente(jtf_nomeCB.getText(), 1);
            tela1.setVisible(true);
        
        }
             
        limpatelaCliente();

    }//GEN-LAST:event_jbt_buscaNOMEActionPerformed

    private void jbt_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_sairActionPerformed
        exit(0);
    }//GEN-LAST:event_jbt_sairActionPerformed

    private void jbt_mostraTCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_mostraTCActionPerformed
        //Setar a MostraCliente->Tela1 com os parametros de busca, pode ser feito chamando uma função da tela1
        MostraCliente tela1 = new MostraCliente("", 0);
        tela1.setVisible(true);
    }//GEN-LAST:event_jbt_mostraTCActionPerformed

    private void jbt_adicionarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_adicionarCActionPerformed
        //INSERIR CLIENTE
        if(jtf_cpfC.getText().length() == 11 && jtf_cpfC.getText().matches("[0-9]*")){
            
            Cliente cliente = new Cliente();
        
            cliente.setCpf(jtf_cpfC.getText());
            cliente.setNome(jtf_nomeC.getText());
            cliente.setTelefone(jtf_telefoneC.getText());
            cliente.setEndereco(jtf_enderecoC.getText());
            cliente.setInstagram(jtf_instagramC.getText());
            cliente.setEmail(jtf_emailC.getText());
            cliente.setFacebook(jtf_facebookC.getText());
            cliente.setCartao(jtf_cartaoC.getText());
        
            fabricadao.insertCliente(cliente);
            jtf_numcliente.setText(Integer.toString(Cliente.num_cliente));
            limpatelaCliente();
            
        }else{
            
            JOptionPane.showMessageDialog(rootPane, "O CPF inserido é inválido! Tente novamente.");
        }
        
    }//GEN-LAST:event_jbt_adicionarCActionPerformed

    private void jbt_removerCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_removerCActionPerformed
        
        if(jtf_cpfC.getText().equals("")){
            JOptionPane.showMessageDialog(null, "INFORME O CPF PARA REMOVER!");
        }else{
        
            String cpf = jtf_cpfC.getText();
        
            fabricadao.excluirCliente(cpf);
            jtf_numcliente.setText(Integer.toString(Cliente.num_cliente));
        
        }
             
        limpatelaCliente();
        
    }//GEN-LAST:event_jbt_removerCActionPerformed

    private void jbt_atualizarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_atualizarCActionPerformed
        
        if(jtf_cpfC.getText().equals("")){
            JOptionPane.showMessageDialog(null, "INFORME O CPF PARA ATUALIZAR!");
        }else{
            Cliente cliente = new Cliente();
        
            cliente.setCpf(jtf_cpfC.getText());
            cliente.setNome(jtf_nomeC.getText());
            cliente.setTelefone(jtf_telefoneC.getText());
            cliente.setEndereco(jtf_enderecoC.getText());
            cliente.setInstagram(jtf_instagramC.getText());
            cliente.setEmail(jtf_emailC.getText());
            cliente.setFacebook(jtf_facebookC.getText());
            cliente.setCartao(jtf_cartaoC.getText());
        
            fabricadao.updateCliente(cliente);
            limpatelaCliente();
        }
        
    }//GEN-LAST:event_jbt_atualizarCActionPerformed

    private void jbt_adicionarQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_adicionarQActionPerformed
        //Adicionar queijo
        
        if(!jtf_idqueijo.getText().equals("") && jtf_idqueijo.getText().matches("[0-9]*")){
            
            Queijo queijo = new Queijo();
        
            queijo.setId_queijo(jtf_idqueijo.getText());
            queijo.setLote(jtf_lote.getText());
            queijo.setTipo(jtf_tipo.getText());
            queijo.setValor_venda(Float.parseFloat(jtf_valorVenda.getText()));
            queijo.setPeso(Float.parseFloat(jtf_peso.getText()));
            queijo.setData_fabricacao(LocalDate.parse(jtf_dtFab.getText(), DateTimeFormatter.ofPattern("yyyy/MM/dd")));
            
            fabricadao.insertQueijo(queijo);
            limpatelaQueijo();
        }else{
            JOptionPane.showMessageDialog(rootPane, "O ID inserido para o queijo é inválido! Tente novamente.");
        }
        
    }//GEN-LAST:event_jbt_adicionarQActionPerformed

    private void jbt_removerQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_removerQActionPerformed
        
        String id_queijo = jtf_idqueijo.getText();
        
        if(jtf_idqueijo.getText().equals("")){
            JOptionPane.showMessageDialog(null, "INFORME O ID DO QUEIJO PARA REMOVER");
        }else{
            fabricadao.excluirQueijo(id_queijo);
        }
        limpatelaQueijo();
   
        
    }//GEN-LAST:event_jbt_removerQActionPerformed

    private void jbt_atualizarQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_atualizarQActionPerformed
        
        if(jtf_idqueijo.getText().equals("")){
            
            JOptionPane.showMessageDialog(null, "INFORME O ID DO QUEIJO PARA REMOVER");
        }else{
            
            Queijo queijo = new Queijo();
        
            queijo.setId_queijo(jtf_idqueijo.getText());
            queijo.setLote(jtf_lote.getText());
            queijo.setTipo(jtf_tipo.getText());
            queijo.setValor_venda(Float.parseFloat(jtf_valorVenda.getText()));
            queijo.setPeso(Float.parseFloat(jtf_peso.getText()));
            queijo.setData_fabricacao(LocalDate.parse(jtf_dtFab.getText(), DateTimeFormatter.ofPattern("yyyy/MM/dd")));
        
            fabricadao.updateQueijo(queijo);
            limpatelaQueijo();
        }
    }//GEN-LAST:event_jbt_atualizarQActionPerformed

    private void jbt_buscaLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_buscaLoteActionPerformed
        if(jtf_loteB.getText().equals("")){
            JOptionPane.showMessageDialog(null, "INFORME O LOTE PARA BUSCAR");
        }else{
            
            MostraQueijo tela2 = new MostraQueijo(jtf_loteB.getText(), 1);
            tela2.setVisible(true);
        }
        
        limpatelaQueijo();
        
    }//GEN-LAST:event_jbt_buscaLoteActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
            MostraQueijo tela2 = new MostraQueijo("", 0);
            tela2.setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jbt_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_addActionPerformed
       
        QueijoPedido Qpedido = new QueijoPedido();
         
        if(!jtf_cpfclienteP.getText().equals(ClienteAtual) && !listaQpedidos.isEmpty()){  //Se o usuário alterar o cpf antes de finalizar os pedidos, todos os queijos selecionados anteriormente serão perdidos
            listaQpedidos.clear();     
        }
        
        if(jtf_cpfclienteP.getText().length() == 11 && jtf_cpfclienteP.getText().matches("[0-9]*") && !jtf_IDqueijo.getText().equals("") && jtf_IDqueijo.getText().matches("[0-9]*")){
            
            Qpedido.setId_queijo(jtf_IDqueijo.getText());
            Qpedido.setId_queijo_pedido(Integer.toString(listaQpedidos.size() + 1));
            Qpedido.setQnt(Integer.parseInt(jtf_qtd.getText()));
            listaQpedidos.add(Qpedido);
            ClienteAtual = jtf_cpfclienteP.getText();
            JOptionPane.showMessageDialog(null, "\n Queijo adicionado com sucesso.");  
            
        }else{
            JOptionPane.showMessageDialog(null, "O ID do queijo ou CPF inválido! Verifique as informações.");
        }
        
        
    }//GEN-LAST:event_jbt_addActionPerformed

    private void jbt_finalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_finalizarActionPerformed
        
        if(listaQpedidos.isEmpty()){
            
            JOptionPane.showMessageDialog(null, "O pedido está vazio, insira algum queijo antes de finalizá-lo!");
        }else{
            
            Pedido pedido = new Pedido();
            String id = Integer.toString(pedido.hashCode());
        
            pedido.setId_pedido(id);
            pedido.setCpf(ClienteAtual);
            pedido.setPrazo_entrega(Integer.parseInt(jtf_prazo.getText()));
            pedido.setData(LocalDate.now());
            
            for(QueijoPedido var : listaQpedidos){
                var.setId_pedido(id);
            }
        
            fabricadao.insertPedido(pedido, listaQpedidos);
            listaQpedidos.clear();
            limpatelaPedido();
        }
        
    }//GEN-LAST:event_jbt_finalizarActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        if(jtf_idpedido2.getText().equals("")){
            JOptionPane.showMessageDialog(null, "INFORME O ID DO PEDIDO PARA REMOVER");
        }else{
            fabricadao.excluirPedido(jtf_idpedido2.getText());
            limpatelaPedido();
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jbt_buscarPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_buscarPedidosActionPerformed
        if(jtf_cpfclienteP.getText().equals("")){
            JOptionPane.showMessageDialog(null, "INFORME O CPF DO CLIENTE PARA BUSCAR");
        }else{
            TelaPedidoCliente tela3 = new TelaPedidoCliente(jtf_cpfclienteP.getText());
            tela3.setVisible(true);
        }
        
    }//GEN-LAST:event_jbt_buscarPedidosActionPerformed

    private void btf_mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btf_mostrarActionPerformed
        MostraTodosPedidos tela4 =  new MostraTodosPedidos();
        tela4.setVisible(true);
    }//GEN-LAST:event_btf_mostrarActionPerformed

    private void jbt_removerQueijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_removerQueijoActionPerformed
        
        if(jtf_idpedido2.getText().equals("") || jtf_idqueijo2.getText().equals("")){
            JOptionPane.showMessageDialog(null, "PREENCHA OS DOIS CAMPOS ACIMA PARA REMOVER UM QUEIJO DE UM PEDIDO");
        }else{
            fabricadao.excluirQueijoPedido(jtf_idpedido2.getText(), jtf_idqueijo2.getText());
            limpatelaPedido();
        }
        
    }//GEN-LAST:event_jbt_removerQueijoActionPerformed

    /**
     * @param args the command line arguments
     */
    private void limpatelaCliente(){
        
        jtf_cpfC.setText("");
        jtf_nomeC.setText("");
        jtf_telefoneC.setText("");
        jtf_enderecoC.setText("");
        jtf_instagramC.setText("");
        jtf_emailC.setText("");
        jtf_facebookC.setText("");
        jtf_cartaoC.setText("");
        jtf_cpfCB.setText("");
        jtf_nomeCB.setText("");
        
    }
    
    private void limpatelaQueijo(){
        
        jtf_idqueijo.setText("");
        jtf_lote.setText("");
        jtf_tipo.setText("");
        jtf_valorVenda.setText("");
        jtf_peso.setText("");
        jtf_dtFab.setText("");
        
    }
    
    private void limpatelaPedido(){
        
        jtf_IDqueijo.setText("");
        jtf_qtd.setText("");
        jtf_prazo.setText("");
        jtf_cpfclienteP.setText("");
        jtf_idpedido2.setText("");
        jtf_idqueijo2.setText("");
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
                
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btf_mostrar;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbt_add;
    private javax.swing.JButton jbt_adicionarC;
    private javax.swing.JButton jbt_adicionarQ;
    private javax.swing.JButton jbt_atualizarC;
    private javax.swing.JButton jbt_atualizarQ;
    private javax.swing.JButton jbt_buscaCPF;
    private javax.swing.JButton jbt_buscaLote;
    private javax.swing.JButton jbt_buscaNOME;
    private javax.swing.JButton jbt_buscarPedidos;
    private javax.swing.JButton jbt_finalizar;
    private javax.swing.JButton jbt_mostraTC;
    private javax.swing.JButton jbt_removerC;
    private javax.swing.JButton jbt_removerQ;
    private javax.swing.JButton jbt_removerQueijo;
    private javax.swing.JButton jbt_sair;
    private javax.swing.JTextField jtf_IDqueijo;
    private javax.swing.JTextField jtf_cartaoC;
    private javax.swing.JTextField jtf_cpfC;
    private javax.swing.JTextField jtf_cpfCB;
    private javax.swing.JTextField jtf_cpfclienteP;
    private javax.swing.JFormattedTextField jtf_dtFab;
    private javax.swing.JTextField jtf_emailC;
    private javax.swing.JTextField jtf_enderecoC;
    private javax.swing.JTextField jtf_facebookC;
    private javax.swing.JTextField jtf_idpedido2;
    private javax.swing.JTextField jtf_idqueijo;
    private javax.swing.JTextField jtf_idqueijo2;
    private javax.swing.JTextField jtf_instagramC;
    private javax.swing.JTextField jtf_lote;
    private javax.swing.JTextField jtf_loteB;
    private javax.swing.JTextField jtf_nomeC;
    private javax.swing.JTextField jtf_nomeCB;
    private javax.swing.JTextField jtf_numcliente;
    private javax.swing.JTextField jtf_peso;
    private javax.swing.JTextField jtf_prazo;
    private javax.swing.JTextField jtf_qtd;
    private javax.swing.JTextField jtf_telefoneC;
    private javax.swing.JTextField jtf_tipo;
    private javax.swing.JTextField jtf_valorVenda;
    // End of variables declaration//GEN-END:variables
}
